import 'package:feed_estimator/src/core/constants/common.dart';
import 'package:flutter/material.dart';

class About extends StatelessWidget {
  const About({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return AboutDialog(
      // applicationName: 'Ebena Feed Estimator',
      applicationVersion: 'v1.0.0',

      applicationIcon: const CircleAvatar(
          child: Image(image: AssetImage('assets/images/logo.png'))),
      applicationLegalese: '(c) ${DateTime.now().year} All Right Reserved',

      children: [
        const Card(
          child: Column(
            children: [
              SizedBox(
                height: 20,
              ),
              Text('Designed By:',
                  style: TextStyle(fontWeight: FontWeight.bold)),
              Image(
                image: AssetImage('assets/images/ebena.png'),
                width: 140,
              ),
              Text(
                'Ebena Agro Ltd | +2348067150455',
                style: TextStyle(fontWeight: FontWeight.bold),
              ),
              Text(
                'http://ebena.com.ng',
                style: TextStyle(fontWeight: FontWeight.bold),
              ),
              SizedBox(
                height: 20,
              )
            ],
          ),
        ),
        Card(
          color: Colors.grey,
          child: Column(
            children: [
              const Text('Credit:',
                  style: TextStyle(fontWeight: FontWeight.bold)),
              paddedText(
                  'The proximate analysis, data and information used for developing this application are sourced majorly from the following sources : 1. INRA-CIRAD-AFZ Feed tables, 2018, (www.feedtables.com); 2. Nutrient Requirements of Swine 11th Rev. Ed., 2012, National Research Council of The National Academies; 3. AmiPig - illeal standardised digestibility of amino acids in feedstuffs for pigs, 2000, AFZ, Ajinomoto Eurolysine, Aventis Animal Nutrition, INRA, ITCF; 4. Swine Nutrition Guide, 2000, http://ianrwww.unl.edu/pubs/swine/ec273.htm); 5. Evapig; 6. NIAS;  7. CVB Feed Table 2016, (www.cvbdiervoeding.nl), FNB',
                  align: TextAlign.justify),
            ],
          ),
        ),
        Card(
          color: AppConstants.appCarrotColor,
          child: Column(
            children: [
              const Text('Disclaimer:',
                  style: TextStyle(fontWeight: FontWeight.bold)),
              paddedText(
                  'Feed Estimator is designed, developed and built by https://twitter.com/ebena107 for Ebena Agro Ltd, Ejigbo, Osun State Nigeria. It is release on MIT licence by Ebena Agro Ltd. By downloading and using this app, you accept, unconditionally that, Ebena Agro Ltd (or designers of this app), or any of its subsidiaries, or any person associated with it, shall not be held liable by any person, or organization,or nation for any direct or indirect damages arising from any use of Feed Estimator and/or the data generated by Feed Estimator. It is explicitly stated that any financial or commercial loss (for instance: loss of data, loss of customers or of orders, loss of benefit, operating loss, opportunity loss, commercial trouble) or any action directed against Feed Estimator by a third party constitutes an indirect damage and is not eligible for compensation of damage by Ebena Agro Ltd.',
                  align: TextAlign.justify),
            ],
          ),
        ),
      ],
    );
  }
}

Widget paddedText(final String text,
        {final TextAlign align = TextAlign.left}) =>
    Padding(
      padding: const EdgeInsets.all(10),
      child: Text(text, textAlign: align, style: const TextStyle(fontSize: 10)),
    );
